# Generated by Django 3.2.2 on 2021-06-22 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('fraction_appointment', models.DecimalField(decimal_places=2, max_digits=3)),
                ('appointment_adjustment', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(max_length=300)),
                ('module_title', models.CharField(max_length=300)),
                ('total_hours', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkloadScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=300, unique=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_hours', models.PositiveIntegerField()),
                ('assigned_lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workload_app.lecturer')),
                ('assigned_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workload_app.module')),
                ('workload_scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workload_app.workloadscenario')),
            ],
            options={
                'ordering': ['number_of_hours'],
            },
        ),
    ]
