# Generated by Django 3.2.2 on 2021-06-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workloadscenario',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
