# Generated by Django 2.2.20 on 2021-09-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0003_auto_20210904_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='module_type',
            field=models.CharField(choices=[('Not assigned', 'Module type not yet assigned'), ('Core', 'Core module'), ('Elective', 'Elective module'), ('Faculty module', 'Facult module')], default='Not assigned', max_length=300),
        ),
    ]
