# Generated by Django 2.2.20 on 2021-09-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0004_module_module_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='tutorial_groups',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
