# Generated by Django 2.2.20 on 2021-09-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0005_module_tutorial_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='tutorial_groups',
            new_name='number_of_tutorial_groups',
        ),
        migrations.AlterField(
            model_name='module',
            name='module_type',
            field=models.CharField(choices=[('Not assigned', 'Module type not yet assigned'), ('Core', 'Core module'), ('Elective', 'Elective module'), ('Faculty module', 'Faculty module')], default='Not assigned', max_length=300),
        ),
    ]
