# Generated by Django 2.2.20 on 2021-09-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0006_auto_20210904_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='module_code',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
