# Generated by Django 2.2.20 on 2021-10-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0007_auto_20210925_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
