# Generated by Django 2.2.20 on 2021-10-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0008_auto_20211002_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='name',
            field=models.CharField(error_messages={'unique': 'Name already exists'}, max_length=300, unique=True),
        ),
    ]
