# Generated by Django 2.2.20 on 2021-10-02 13:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0010_auto_20211002_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='fraction_appointment',
            field=models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
    ]
