# Generated by Django 2.2.20 on 2021-10-16 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0012_auto_20211002_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='name',
            field=models.CharField(error_messages={'unique': 'Name of lecturers already exists, please choose another one'}, max_length=300),
        ),
    ]
