# Generated by Django 2.2.20 on 2021-10-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0013_auto_20211016_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='module',
            name='module_code',
            field=models.CharField(max_length=300),
        ),
    ]
