# Generated by Django 2.2.20 on 2021-10-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0014_auto_20211016_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workloadscenario',
            name='label',
            field=models.CharField(max_length=300),
        ),
    ]
