# Generated by Django 2.2.20 on 2021-11-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0015_auto_20211023_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='semester_offered',
            field=models.CharField(choices=[('Not assigned', 'No semester assigned yet'), ('Semester 1', 'Semester 1'), ('Semester 2', 'Semester 2'), ('Special term 1', 'Special term 1'), ('Special term 2', 'Special term 2')], default='Not assigned', max_length=300),
        ),
    ]
