# Generated by Django 2.2.20 on 2021-11-04 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0016_module_semester_offered'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours', models.PositiveIntegerField()),
                ('module_type', models.CharField(choices=[('Not assigned', 'Module type not yet assigned'), ('Core', 'Core module'), ('Elective', 'Elective module'), ('Faculty module', 'Faculty module')], default='Not assigned', max_length=300)),
                ('semester_offered', models.CharField(choices=[('Not assigned', 'No semester assigned yet'), ('Semester 1', 'Semester 1'), ('Semester 2', 'Semester 2'), ('Special term 1', 'Special term 1'), ('Special term 2', 'Special term 2')], default='Not assigned', max_length=300)),
                ('number_of_tutorial_groups', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='module',
            name='module_type',
        ),
        migrations.RemoveField(
            model_name='module',
            name='number_of_tutorial_groups',
        ),
        migrations.RemoveField(
            model_name='module',
            name='semester_offered',
        ),
        migrations.RemoveField(
            model_name='module',
            name='total_hours',
        ),
        migrations.AddField(
            model_name='module',
            name='module_features',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workload_app.ModuleFeatures'),
        ),
    ]
