# Generated by Django 2.2.20 on 2021-11-04 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0017_auto_20211104_0653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='module_features',
        ),
        migrations.AddField(
            model_name='modulefeatures',
            name='module_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workload_app.Module'),
        ),
    ]
