# Generated by Django 2.2.20 on 2021-11-06 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0018_auto_20211104_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulefeatures',
            name='scenario_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workload_app.WorkloadScenario'),
        ),
    ]
