# Generated by Django 2.2.20 on 2021-11-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0020_auto_20211114_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulefeatures',
            name='total_hours',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
