# Generated by Django 2.2.20 on 2021-11-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0023_auto_20211114_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
