# Generated by Django 2.2.20 on 2021-11-26 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0024_module_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='name_without_spaces',
            field=models.CharField(default='', max_length=300),
        ),
    ]
