# Generated by Django 2.2.20 on 2021-11-26 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0025_lecturer_name_without_spaces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='name_without_spaces',
        ),
    ]
