# Generated by Django 2.2.20 on 2021-11-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0026_remove_lecturer_name_without_spaces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulefeatures',
            name='module_type',
            field=models.CharField(choices=[('Not assigned', 'Module type not yet assigned'), ('Core', 'Core module'), ('Elective', 'Elective module'), ('Design module', 'Design module'), ('Faculty module', 'Faculty module'), ('EPP module', 'EPP module')], default='Not assigned', max_length=300),
        ),
    ]
