# Generated by Django 2.2.20 on 2021-11-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0027_auto_20211129_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulefeatures',
            name='semester_offered',
            field=models.CharField(choices=[('Not assigned', 'No semester assigned yet'), ('Semester 1', 'Semester 1'), ('Semester 2', 'Semester 2'), ('Sem 1 and sem 2', 'Sem 1 and sem 2'), ('Special term 1', 'Special term 1'), ('Special term 2', 'Special term 2')], default='Not assigned', max_length=300),
        ),
    ]
