# Generated by Django 2.2.20 on 2021-12-02 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0028_auto_20211129_0834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['module_code']},
        ),
    ]
