# Generated by Django 3.2.9 on 2021-12-03 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0030_auto_20211202_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='active',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='workload_scenario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workload_app.workloadscenario'),
        ),
        migrations.AddField(
            model_name='module',
            name='module_type',
            field=models.CharField(choices=[('Not assigned', 'Module type not yet assigned'), ('Core', 'Core module'), ('Elective', 'Elective module'), ('Design module', 'Design module'), ('Faculty module', 'Faculty module'), ('EPP module', 'EPP module')], default='Not assigned', max_length=300),
        ),
        migrations.AddField(
            model_name='module',
            name='number_of_tutorial_groups',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='module',
            name='scenario_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workload_app.workloadscenario'),
        ),
        migrations.AddField(
            model_name='module',
            name='semester_offered',
            field=models.CharField(choices=[('Not assigned', 'No semester assigned yet'), ('Semester 1', 'Semester 1'), ('Semester 2', 'Semester 2'), ('Sem 1 and sem 2', 'Sem 1 and sem 2'), ('Special term 1', 'Special term 1'), ('Special term 2', 'Special term 2')], default='Not assigned', max_length=300),
        ),
        migrations.AddField(
            model_name='module',
            name='total_hours',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='ModuleFeatures',
        ),
    ]
