# Generated by Django 3.2.9 on 2021-12-03 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0031_auto_20211203_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='scenario_ref',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workload_app.workloadscenario'),
        ),
    ]
