# Generated by Django 3.2.9 on 2021-12-10 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0032_alter_module_scenario_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ['type_name'],
            },
        ),
    ]
