# Generated by Django 3.2.9 on 2022-02-19 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0033_moduletype'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='module_type_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workload_app.moduletype'),
        ),
    ]
