# Generated by Django 3.2.9 on 2022-02-19 07:04

from django.db import migrations

def fill_mod_type_fk(apps, schema_editor):
  Module = apps.get_model('workload_app', 'Module')
  ModuleType = apps.get_model('workload_app', 'ModuleType')
  for mod in Module.objects.all():
    mod.module_type_fk, created = ModuleType.objects.get_or_create(type_name=mod.module_type)
    mod.save()
    
class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0034_module_module_type_fk'),
    ]

    operations = [
        migrations.RunPython(fill_mod_type_fk),
    ]
