# Generated by Django 3.2.9 on 2022-02-19 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0035_auto_20220219_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='module_type',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='module_type_fk',
            new_name='module_type',
        ),
    ]
