# Generated by Django 3.2.9 on 2022-05-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0036_auto_20220219_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingassignment',
            name='number_of_weekly_lecture_hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='number_of_weekly_tutorial_hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='number_of_weeks',
            field=models.PositiveIntegerField(default=13),
        ),
    ]
