# Generated by Django 3.2.9 on 2022-05-19 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0037_auto_20220516_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachingassignment',
            old_name='number_of_weeks',
            new_name='number_of_weeks_assigned',
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='number_of_tutorial_groups',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
