# Generated by Django 3.2.9 on 2022-05-19 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0038_auto_20220519_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingassignment',
            name='assigned_manually',
            field=models.BooleanField(default=True),
        ),
    ]
