# Generated by Django 3.2.9 on 2022-06-01 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0039_teachingassignment_assigned_manually'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=300)),
                ('department_acronym', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ['department_acronym'],
            },
        ),
    ]
