# Generated by Django 3.2.9 on 2022-06-01 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0040_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='workloadscenario',
            name='dept',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workload_app.department'),
        ),
    ]
