# Generated by Django 3.2.9 on 2022-06-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0041_workloadscenario_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_acronym',
            field=models.CharField(max_length=4),
        ),
    ]
