# Generated by Django 3.2.9 on 2022-06-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0042_alter_department_department_acronym'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ['track_name'],
            },
        ),
    ]
