# Generated by Django 3.2.9 on 2022-06-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0043_employmenttrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmenttrack',
            name='track_adjustment',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
            preserve_default=False,
        ),
    ]
