# Generated by Django 3.2.9 on 2022-06-02 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0044_employmenttrack_track_adjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmenttrack',
            name='track_adjustment',
            field=models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
