# Generated by Django 3.2.6 on 2022-06-03 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0045_alter_employmenttrack_track_adjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='employment_track',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workload_app.employmenttrack'),
        ),
    ]
