# Generated by Django 3.2.6 on 2022-06-03 10:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0046_lecturer_employment_track'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=300)),
                ('role_adjustment', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ['role_name'],
            },
        ),
        migrations.AlterField(
            model_name='employmenttrack',
            name='track_adjustment',
            field=models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)]),
        ),
    ]
