# Generated by Django 3.2.9 on 2022-06-04 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0047_auto_20220603_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='service_role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workload_app.servicerole'),
        ),
    ]
