# Generated by Django 3.2.9 on 2022-06-05 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0048_lecturer_service_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='appointment_adjustment',
        ),
    ]
