# Generated by Django 3.2.12 on 2022-09-18 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0049_remove_lecturer_appointment_adjustment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workloadscenario',
            name='is_active',
        ),
    ]
