# Generated by Django 3.2.12 on 2022-10-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0050_remove_workloadscenario_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=300)),
                ('faculty_acronym', models.CharField(max_length=4)),
            ],
            options={
                'ordering': ['faculty_acronym'],
            },
        ),
    ]
