# Generated by Django 3.2.6 on 2022-10-04 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0052_department_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academicyear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2200), django.core.validators.MinValueValidator(1900)])),
            ],
        ),
    ]
