# Generated by Django 3.2.6 on 2022-10-04 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0053_academicyear'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicyear',
            options={'ordering': ['start_year']},
        ),
        migrations.AddField(
            model_name='workloadscenario',
            name='academic_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workload_app.academicyear'),
        ),
    ]
