# Generated by Django 3.2.6 on 2022-10-04 09:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0054_auto_20221004_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='start_year',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(2200), django.core.validators.MinValueValidator(1900)]),
        ),
    ]
