# Generated by Django 3.2.12 on 2022-10-18 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0055_alter_academicyear_start_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='workloadscenario',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Official', 'Official')], default='Draft', max_length=50),
        ),
    ]
