# Generated by Django 3.2.12 on 2023-02-25 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0056_workloadscenario_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkloadPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=300, unique=True)),
                ('employment_tracks', models.ManyToManyField(to='workload_app.EmploymentTrack')),
                ('service_roles', models.ManyToManyField(to='workload_app.ServiceRole')),
            ],
        ),
        migrations.AddField(
            model_name='workloadscenario',
            name='workload_policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workload_app.workloadpolicy'),
        ),
    ]
