# Generated by Django 4.1.2 on 2023-02-26 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workload_app", "0057_auto_20230225_0752"),
    ]

    operations = [
        migrations.AddField(
            model_name="employmenttrack",
            name="is_default",
            field=models.BooleanField(default=True),
        ),
    ]
