# Generated by Django 4.1.2 on 2023-02-26 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workload_app", "0059_alter_employmenttrack_is_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerole",
            name="is_default",
            field=models.BooleanField(default=True, null=True),
        ),
    ]
