# Generated by Django 3.2.12 on 2023-03-12 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0060_servicerole_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workloadscenario',
            name='workload_policy',
        ),
        migrations.DeleteModel(
            name='WorkloadPolicy',
        ),
    ]
