# Generated by Django 4.1.2 on 2023-05-06 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workload_app", "0061_auto_20230312_0715"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgrammeOffered",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("programme_name", models.CharField(max_length=300)),
                (
                    "primary_dept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workload_app.department",
                    ),
                ),
            ],
        ),
    ]
