# Generated by Django 4.1.2 on 2023-05-07 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workload_app", "0062_programmeoffered"),
    ]

    operations = [
        migrations.AddField(
            model_name="programmeoffered",
            name="acad_year",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="workload_app.academicyear",
            ),
            preserve_default=False,
        ),
    ]
