# Generated by Django 3.2.6 on 2023-05-26 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0064_remove_programmeoffered_acad_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='primary_programme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workload_app.programmeoffered'),
        ),
    ]
