# Generated by Django 3.2.6 on 2023-08-03 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0066_alter_module_primary_programme'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmenttrack',
            name='counts_towards_fte',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
