# Generated by Django 3.2.6 on 2023-08-03 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0067_employmenttrack_counts_towards_fte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employmenttrack',
            old_name='counts_towards_fte',
            new_name='is_adjunct',
        ),
    ]
