# Generated by Django 3.2.6 on 2023-08-03 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0068_rename_counts_towards_fte_employmenttrack_is_adjunct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmenttrack',
            name='is_adjunct',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
