# Generated by Django 3.2.12 on 2023-08-20 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0069_alter_employmenttrack_is_adjunct'),
    ]

    operations = [
        migrations.CreateModel(
            name='StduentLearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slo_description', models.CharField(max_length=3000)),
                ('is_default_by_accreditor', models.BooleanField(default=False)),
                ('letter_associated', models.CharField(default='zz', max_length=2)),
            ],
            options={
                'ordering': ['letter_associated'],
            },
        ),
    ]
