# Generated by Django 3.2.12 on 2023-08-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0070_stduentlearningoutcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stduentlearningoutcome',
            name='letter_associated',
            field=models.CharField(default='', max_length=2),
        ),
    ]
