# Generated by Django 3.2.6 on 2023-08-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0071_alter_stduentlearningoutcome_letter_associated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='primary_programme',
        ),
        migrations.AddField(
            model_name='module',
            name='primary_programme',
            field=models.ManyToManyField(null=True, to='workload_app.ProgrammeOffered'),
        ),
    ]
