# Generated by Django 3.2.6 on 2023-08-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0072_auto_20230821_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='primary_programme',
            field=models.ManyToManyField(to='workload_app.ProgrammeOffered'),
        ),
    ]
