# Generated by Django 3.2.6 on 2023-08-22 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0073_alter_module_primary_programme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='primary_programme',
        ),
        migrations.AddField(
            model_name='module',
            name='primary_programme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workload_app.programmeoffered'),
        ),
    ]
