# Generated by Django 3.2.6 on 2023-08-22 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0074_auto_20230822_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='secondary_programme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_programme', to='workload_app.programmeoffered'),
        ),
        migrations.AlterField(
            model_name='module',
            name='primary_programme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_programme', to='workload_app.programmeoffered'),
        ),
    ]
