# Generated by Django 3.2.6 on 2023-08-22 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0075_auto_20230822_0450'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubProgrammeOffered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_programme_name', models.CharField(max_length=300)),
                ('main_programme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workload_app.programmeoffered')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='sub_programme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workload_app.subprogrammeoffered'),
        ),
    ]
