# Generated by Django 3.2.6 on 2023-08-24 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0076_auto_20230822_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='secondary_sub_programme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_sub_programme', to='workload_app.subprogrammeoffered'),
        ),
        migrations.AlterField(
            model_name='module',
            name='sub_programme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_programme', to='workload_app.subprogrammeoffered'),
        ),
    ]
