# Generated by Django 3.2.12 on 2023-09-03 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0077_auto_20230824_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='stduentlearningoutcome',
            name='programme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workload_app.programmeoffered'),
        ),
    ]
