# Generated by Django 3.2.12 on 2023-09-03 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0078_stduentlearningoutcome_programme'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StduentLearningOutcome',
            new_name='StudentLearningOutcome',
        ),
    ]
