# Generated by Django 3.2.12 on 2023-09-03 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0079_rename_stduentlearningoutcome_studentlearningoutcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammeEducationalObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peo_description', models.CharField(max_length=3000)),
                ('letter_associated', models.CharField(default='', max_length=2)),
                ('programme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workload_app.programmeoffered')),
            ],
            options={
                'ordering': ['letter_associated'],
            },
        ),
    ]
