# Generated by Django 3.2.6 on 2023-09-05 05:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0080_programmeeducationalobjective'),
    ]

    operations = [
        migrations.CreateModel(
            name='PEOSLOMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)])),
                ('peo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workload_app.programmeeducationalobjective')),
                ('slo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workload_app.studentlearningoutcome')),
            ],
        ),
    ]
