# Generated by Django 3.2.6 on 2023-09-05 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0081_peoslomapping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peoslomapping',
            options={'ordering': ['peo']},
        ),
    ]
