# Generated by Django 3.2.12 on 2023-09-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0082_alter_peoslomapping_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmeeducationalobjective',
            name='peo_short_description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='studentlearningoutcome',
            name='slo_short_description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
