# Generated by Django 3.2.6 on 2023-09-12 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0083_auto_20230909_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingassignment',
            name='counted_towards_workload',
            field=models.BooleanField(default=True),
        ),
    ]
