# Generated by Django 3.2.12 on 2023-09-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0084_teachingassignment_counted_towards_workload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleLearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mlo_description', models.CharField(max_length=3000)),
                ('mlo_short_description', models.CharField(default='', max_length=500)),
                ('module_code', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ['mlo_description'],
            },
        ),
    ]
