# Generated by Django 3.2.12 on 2023-09-24 04:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0085_modulelearningoutcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLOSLOMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)])),
                ('mlo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workload_app.modulelearningoutcome')),
                ('slo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workload_app.studentlearningoutcome')),
            ],
            options={
                'ordering': ['mlo'],
            },
        ),
    ]
