# Generated by Django 3.2.6 on 2023-09-27 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0086_mloslomapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_title', models.CharField(max_length=3000)),
                ('original_file', models.FileField(upload_to='surveys/')),
                ('opening_date', models.DateField()),
                ('closing_date', models.DateField()),
                ('max_respondents', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=3000)),
                ('n_highest_score', models.IntegerField(default=-1)),
                ('n_second_highest_score', models.IntegerField(default=-1)),
                ('n_third_highest_score', models.IntegerField(default=-1)),
                ('n_fourth_highest_score', models.IntegerField(default=-1)),
                ('n_fifth_highest_score', models.IntegerField(default=-1)),
                ('n_sixth_highest_score', models.IntegerField(default=-1)),
                ('text_response', models.CharField(default='', max_length=60000)),
                ('associated_mlo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workload_app.modulelearningoutcome')),
                ('associated_peo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workload_app.programmeeducationalobjective')),
                ('associated_slo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workload_app.studentlearningoutcome')),
                ('parent_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workload_app.survey')),
            ],
            options={
                'ordering': ['question_text'],
            },
        ),
    ]
