# Generated by Django 3.2.12 on 2023-10-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0087_survey_surveyquestionresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestionresponse',
            name='label_fifth_highest_score',
            field=models.CharField(default='Strongly disagree', max_length=350),
        ),
        migrations.AddField(
            model_name='surveyquestionresponse',
            name='label_fourth_highest_score',
            field=models.CharField(default='Disagree', max_length=350),
        ),
        migrations.AddField(
            model_name='surveyquestionresponse',
            name='label_highest_score',
            field=models.CharField(default='Strongly agree', max_length=350),
        ),
        migrations.AddField(
            model_name='surveyquestionresponse',
            name='label_second_highest_score',
            field=models.CharField(default='Agree', max_length=350),
        ),
        migrations.AddField(
            model_name='surveyquestionresponse',
            name='label_sixth_highest_score',
            field=models.CharField(default='', max_length=350),
        ),
        migrations.AddField(
            model_name='surveyquestionresponse',
            name='label_third_highest_score',
            field=models.CharField(default='Neutral', max_length=350),
        ),
    ]
