# Generated by Django 3.2.12 on 2023-10-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0088_auto_20231001_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='comments',
            field=models.CharField(default='', max_length=50000),
        ),
    ]
