# Generated by Django 3.2.12 on 2023-10-15 10:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0089_survey_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLOPerformanceMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100000)),
                ('percentage_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('original_file', models.FileField(upload_to='mlo_performance_measures/')),
                ('academic_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workload_app.academicyear')),
                ('associated_mlo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workload_app.modulelearningoutcome')),
            ],
        ),
    ]
