# Generated by Django 3.2.12 on 2023-10-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0090_mloperformancemeasure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='original_file',
            field=models.FileField(upload_to='surveys'),
        ),
    ]
