# Generated by Django 3.2.12 on 2023-11-05 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0091_alter_survey_original_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='mloperformancemeasure',
            name='secondary_associated_mlo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_mlo', to='workload_app.modulelearningoutcome'),
        ),
        migrations.AddField(
            model_name='mloperformancemeasure',
            name='tertiary_associated_mlo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tertiary_mlo', to='workload_app.modulelearningoutcome'),
        ),
    ]
