# Generated by Django 4.1.2 on 2023-11-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workload_app", "0092_auto_20231105_0521"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mloperformancemeasure",
            name="original_file",
            field=models.FileField(upload_to="mlo_performance_measures"),
        ),
    ]
