# Generated by Django 5.0.1 on 2024-12-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workload_app", "0093_alter_mloperformancemeasure_original_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="compulsory_in_primary_programme",
            field=models.BooleanField(default=False),
        ),
    ]
