# Generated by Django 3.2.12 on 2024-12-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0094_module_compulsory_in_primary_programme'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='students_year_of_study',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
