# Generated by Django 3.2.12 on 2024-12-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0095_module_students_year_of_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='students_year_of_study',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
