# Generated by Django 3.2.12 on 2024-12-22 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0096_alter_module_students_year_of_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='cohort_targeted',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workload_app.academicyear'),
        ),
    ]
