# Generated by Django 3.2.12 on 2025-01-05 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0098_auto_20250105_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmeeducationalobjective',
            name='peo_cohort_valid_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peo_cohort_valid_from', to='workload_app.academicyear'),
        ),
        migrations.AddField(
            model_name='programmeeducationalobjective',
            name='peo_cohort_valid_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peo_cohort_valid_to', to='workload_app.academicyear'),
        ),
    ]
