# Generated by Django 5.0.1 on 2025-01-08 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workload_app", "0100_modulelearningoutcome_mlo_valid_from_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorrectiveActions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=1000000)),
                ("observed_results", models.CharField(max_length=1000000)),
                (
                    "implementation_acad_year",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="workload_app.academicyear",
                    ),
                ),
            ],
        ),
    ]
