# Generated by Django 5.0.1 on 2025-01-08 03:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workload_app", "0101_correctiveactions"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CorrectiveActions",
            new_name="CorrectiveAction",
        ),
    ]
