# Generated by Django 5.0.1 on 2025-01-08 03:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workload_app", "0102_rename_correctiveactions_correctiveaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="correctiveaction",
            name="module_code",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
    ]
