# Generated by Django 5.0.1 on 2025-01-14 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workload_app", "0103_correctiveaction_module_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="moduletype",
            name="department",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="workload_app.department",
            ),
        ),
    ]
