# Generated by Django 5.0.1 on 2025-01-14 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workload_app", "0104_moduletype_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="module_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="workload_app.moduletype",
            ),
        ),
    ]
