# Generated by Django 5.0.1 on 2025-01-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workload_app", "0106_universitystaff"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="num_answers",
            field=models.IntegerField(default=-1),
        ),
    ]
