# Generated by Django 5.0.1 on 2025-01-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workload_app", "0107_survey_num_answers"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyquestionresponse",
            name="label_eighth_highest_score",
            field=models.CharField(default="", max_length=350),
        ),
        migrations.AddField(
            model_name="surveyquestionresponse",
            name="label_ninth_highest_score",
            field=models.CharField(default="", max_length=350),
        ),
        migrations.AddField(
            model_name="surveyquestionresponse",
            name="label_seventh_highest_score",
            field=models.CharField(default="", max_length=350),
        ),
        migrations.AddField(
            model_name="surveyquestionresponse",
            name="label_tenth_highest_score",
            field=models.CharField(default="", max_length=350),
        ),
        migrations.AddField(
            model_name="surveyquestionresponse",
            name="n_eighth_highest_score",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="surveyquestionresponse",
            name="n_ninth_highest_score",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="surveyquestionresponse",
            name="n_seventh_highest_score",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="surveyquestionresponse",
            name="n_tenth_highest_score",
            field=models.IntegerField(default=-1),
        ),
    ]
