# Generated by Django 5.0.3 on 2025-01-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0108_surveyquestionresponse_label_eighth_highest_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='survey_type',
            field=models.CharField(choices=[('PEO', 'PEO Survey'), ('SLO', 'SLO Survey'), ('MLO', 'MLO Survey'), ('Undefined', 'Other')], default='Undefined', max_length=10),
        ),
    ]
