# Generated by Django 5.0.3 on 2025-01-29 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0109_survey_survey_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='programme_associated',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='workload_app.programmeoffered'),
            preserve_default=False,
        ),
    ]
