# Generated by Django 5.0.3 on 2025-01-30 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0110_survey_programme_associated'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyLabelSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_score_label', models.CharField(default='', max_length=150)),
                ('second_highest_score_label', models.CharField(default='', max_length=150)),
                ('third_highest_score_label', models.CharField(default='', max_length=150)),
                ('fourth_highest_score_label', models.CharField(default='', max_length=150)),
                ('fifth_highest_score_label', models.CharField(default='', max_length=150)),
                ('sixth_highest_score_label', models.CharField(default='', max_length=150)),
                ('seventh_highest_score_label', models.CharField(default='', max_length=150)),
                ('eighth_highest_score_label', models.CharField(default='', max_length=150)),
                ('ninth_highest_score_label', models.CharField(default='', max_length=150)),
                ('tenth_score_label', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='programmeoffered',
            name='mlo_survey_labels',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mlo_survey_labels', to='workload_app.surveylabelset'),
        ),
        migrations.AddField(
            model_name='programmeoffered',
            name='peo_survey_labels',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peo_survey_labels', to='workload_app.surveylabelset'),
        ),
        migrations.AddField(
            model_name='programmeoffered',
            name='slo_survey_labels',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slo_survey_labels', to='workload_app.surveylabelset'),
        ),
    ]
