# Generated by Django 5.0.3 on 2025-01-31 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0111_surveylabelset_programmeoffered_mlo_survey_labels_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='num_answers',
        ),
        migrations.AddField(
            model_name='survey',
            name='likert_labels',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workload_app.surveylabelset'),
        ),
    ]
