# Generated by Django 5.0.3 on 2025-02-16 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0112_remove_survey_num_answers_survey_likert_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitystaff',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workload_app.faculty'),
        ),
        migrations.AddField(
            model_name='universitystaff',
            name='lecturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workload_app.lecturer'),
        ),
    ]
