# Generated by Django 5.0.3 on 2025-02-16 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0113_universitystaff_faculty_universitystaff_lecturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitystaff',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workload_app.lecturer'),
        ),
    ]
