# Generated by Django 5.0.3 on 2025-02-23 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0114_alter_universitystaff_lecturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmenttrack',
            name='faculty',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workload_app.faculty'),
        ),
        migrations.AddField(
            model_name='servicerole',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workload_app.faculty'),
        ),
    ]
