# Generated by Django 5.0.3 on 2025-03-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0115_employmenttrack_faculty_servicerole_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
    ]
