# Generated by Django 5.0.3 on 2025-03-09 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0116_lecturer_is_external'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='compulsory_in_secondary_programme',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='compulsory_in_tertiary_programme',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='tertirary_programme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tertirary_programme', to='workload_app.programmeoffered'),
        ),
    ]
