# Generated by Django 5.0.3 on 2025-03-09 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0117_module_compulsory_in_secondary_programme_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='tertirary_programme',
            new_name='tertiary_programme',
        ),
    ]
