# Generated by Django 5.0.3 on 2025-06-01 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0118_rename_tertirary_programme_module_tertiary_programme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workload_app.faculty'),
        ),
        migrations.AlterField(
            model_name='employmenttrack',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workload_app.faculty'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='employment_track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workload_app.employmenttrack'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='service_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workload_app.servicerole'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='workload_scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workload_app.workloadscenario'),
        ),
        migrations.AlterField(
            model_name='module',
            name='scenario_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workload_app.workloadscenario'),
        ),
        migrations.AlterField(
            model_name='moduletype',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workload_app.department'),
        ),
        migrations.AlterField(
            model_name='workloadscenario',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workload_app.academicyear'),
        ),
        migrations.AlterField(
            model_name='workloadscenario',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workload_app.department'),
        ),
    ]
