# Generated by Django 5.0.3 on 2025-06-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0119_alter_department_faculty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmenttrack',
            name='is_adjunct',
            field=models.BooleanField(default=False),
        ),
    ]
