# Generated by Django 5.2.3 on 2025-06-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0121_alter_department_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='workloadscenario',
            name='expected_hrs_per_tfte',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=5),
        ),
        migrations.AddField(
            model_name='workloadscenario',
            name='total_hours_delivered',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=5),
        ),
        migrations.AddField(
            model_name='workloadscenario',
            name='total_tfte_used',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=5),
        ),
    ]
