# Generated by Django 5.2.3 on 2025-06-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0122_workloadscenario_expected_hrs_per_tfte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workloadscenario',
            name='expected_hrs_per_tfte',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='workloadscenario',
            name='total_hours_delivered',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='workloadscenario',
            name='total_tfte_used',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=10),
        ),
    ]
