# Generated by Django 5.2.3 on 2025-06-22 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0123_alter_workloadscenario_expected_hrs_per_tfte_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workloadscenario',
            old_name='total_tfte_used',
            new_name='total_tfte_overall',
        ),
    ]
