# Generated by Django 5.2.3 on 2025-06-29 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0124_rename_total_tfte_used_workloadscenario_total_tfte_overall'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingAssignmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=3000)),
                ('quantum_number_of_hours', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='assignnment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workload_app.teachingassignmenttype'),
        ),
    ]
