# Generated by Django 5.2.3 on 2025-06-30 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0125_teachingassignmenttype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingassignmenttype',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workload_app.faculty'),
        ),
    ]
