# Generated by Django 5.0.3 on 2025-07-27 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0126_teachingassignmenttype_faculty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachingassignmenttype',
            options={'ordering': ['quantum_number_of_hours']},
        ),
        migrations.AddField(
            model_name='teachingassignmenttype',
            name='workload_valid_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workload_valid_from', to='workload_app.academicyear'),
        ),
        migrations.AddField(
            model_name='teachingassignmenttype',
            name='workload_valid_until',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workload_valid_until', to='workload_app.academicyear'),
        ),
    ]
