# Generated by Django 5.0.1 on 2025-07-29 03:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workload_app", "0127_alter_teachingassignmenttype_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teachingassignment",
            name="assigned_manually",
        ),
        migrations.RemoveField(
            model_name="teachingassignment",
            name="number_of_tutorial_groups",
        ),
        migrations.RemoveField(
            model_name="teachingassignment",
            name="number_of_weekly_lecture_hours",
        ),
        migrations.RemoveField(
            model_name="teachingassignment",
            name="number_of_weekly_tutorial_hours",
        ),
        migrations.RemoveField(
            model_name="teachingassignment",
            name="number_of_weeks_assigned",
        ),
    ]
