# Generated by Django 5.0.1 on 2025-07-31 05:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workload_app", "0128_remove_teachingassignment_assigned_manually_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="module",
            name="number_of_tutorial_groups",
        ),
    ]
