# Generated by Django 5.2.7 on 2025-10-04 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0129_remove_module_number_of_tutorial_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingassignment',
            name='assigned_lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer', to='workload_app.lecturer'),
        ),
        migrations.AlterField(
            model_name='teachingassignment',
            name='assigned_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module', to='workload_app.module'),
        ),
    ]
