# Generated by Django 5.2.7 on 2025-10-04 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0130_alter_teachingassignment_assigned_lecturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitystaff',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_dept', to='workload_app.department'),
        ),
        migrations.AlterField(
            model_name='universitystaff',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_faculty', to='workload_app.faculty'),
        ),
        migrations.AlterField(
            model_name='universitystaff',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_lecturer', to='workload_app.lecturer'),
        ),
    ]
