# Generated by Django 5.2.7 on 2025-10-05 03:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0131_alter_universitystaff_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitystaff',
            name='departments_in_menu',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='universitystaff',
            name='homepage',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='universitystaff',
            name='lecturers_in_menu',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='universitystaff',
            name='modules_in_menu',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None),
        ),
    ]
