# Generated by Django 5.2.7 on 2025-10-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0132_universitystaff_departments_in_menu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitystaff',
            name='is_menu_populated',
            field=models.BooleanField(default=False),
        ),
    ]
