# Generated by Django 5.2.7 on 2025-10-05 06:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0133_universitystaff_is_menu_populated'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitystaff',
            name='programmes_in_menu',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, size=None),
        ),
    ]
