# Generated by Django 5.2.7 on 2025-10-12 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0134_universitystaff_programmes_in_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachingassignment',
            old_name='assignnment_type',
            new_name='assignment_type',
        ),
    ]
