# Generated by Django 5.2.7 on 2025-11-01 08:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload_app', '0135_rename_assignnment_type_teachingassignment_assignment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitystaff',
            name='modules_in_menu',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=10), blank=True, default=list, size=None),
        ),
    ]
