"""
Django settings for workload_management project.

Generated by 'django-admin startproject' using Django 3.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
from django.core.management.utils import get_random_secret_key
from pathlib import Path
from dotenv import load_dotenv
from django.urls import path
import os 
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv()

ALLOWED_HOSTS = ['104.248.157.119','.localhost','.eabworkload.org','127.0.0.1']

# Application definition
SHARED_APPS = [
    'django_tenants',
    'django.contrib.postgres',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dbbackup',  # django-dbbackup <- requires pip install django-dbbackup
    'django_crontab',
    'landlord',
]

TENANT_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'eduload']

INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]

MIDDLEWARE = [
    'django_tenants.middleware.main.TenantMainMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = True
#SECURE_SSL_REDIRECT = True
CSRF_TRUSTED_ORIGINS = ['https://*.localhost', 'https://localhost', 'https://eabworkload.org', 'https://*.eabworkload.org','http://127.0.0.1:8000']
ROOT_URLCONF = 'workload_management.urls'


INTERNAL_IPS = [
    'localhost',
    "127.0.0.1",
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request'
            ],
        },
    },
]

WSGI_APPLICATION = 'workload_management.wsgi.application'


# Database
# Figure out the git branch we are in, and, based on that, the DB to use
GIT_ROOT_DIR = Path(__file__).resolve().parent.parent.parent
head_file = GIT_ROOT_DIR / ".git" / "HEAD"
branch_name = ''
with head_file.open("r") as f: content = f.read().splitlines()
for line in content:
    if line[0:4] == "ref:":
        branch_name = line.partition("refs/heads/")[2]

NEED_SILK_DEBUG = False #This will be picked up by URL, activate only in development, not testing
if ('devel' in str(branch_name)):
    #print('**** We are using devel settings  *****')
    SECRET_KEY = os.environ["DJANGO_DEVEL_KEY"] #Appended export DJANGO_DEVEL_KEY="*****" at the end of the virtual environment under bin/activate
    DEBUG = True# Development settings have debug=true
    TESTING = "test" in sys.argv
    if TESTING:
        #The pg service does not work for testing (https://code.djangoproject.com/ticket/33685)
        DATABASES = {
        'default': {
            'ENGINE': 'django_tenants.postgresql_backend',
            'NAME' : 'postgres',
            'USER': 'postgres',
            'PASSWORD' : 'postgres',
            'HOST' : '127.0.0.1',
            'PORT' : '5432'
            }
        }
    else: #NOT testing.  
        DATABASES = {
        'default': {
            'ENGINE': 'django_tenants.postgresql_backend',
            'OPTIONS': {
                'service': 'workload_service',
                'passfile': '.pgpass'
            },
        }
        }
        #NEED_SILK_DEBUG=True
        #SILKY_PYTHON_PROFILER=True
        #add the debug silk plugin, disabled for testing
        #INSTALLED_APPS = [
        #    *INSTALLED_APPS,
        #    'silk'
        #]
        #MIDDLEWARE = [
        #    'silk.middleware.SilkyMiddleware',
        #    *MIDDLEWARE,
        #]
        #DISABLE_PANELS = {}

else:
    #print('**** We are using production settings  *****')
    TESTING=False #We only test in devel branch
    if ('production' in str(branch_name)):#the online branch, used for demo
        DEBUG=False #DEBUG must be false in production
        #SESSION_COOKIE_DOMAIN = 'eabworkload.org'
        SESSION_COOKIE_HTTPONLY = True
        SECRET_KEY = os.environ["DJANGO_PRODUCTION_SECRET_KEY"]
        DATABASES = {
        'default': {
            'ENGINE': 'django_tenants.postgresql_backend',
            'OPTIONS': {
                'service': 'workload_service',
                'passfile': '.pgpass',
            },
        }
        }

        #############################
        # Backup-related settings for production DB
        # STORAGES = {
        #     'dbbackup': {
        #         'BACKEND': 'django.core.files.storage.FileSystemStorage',
        #         'OPTIONS': {
        #             'location': os.environ["LOCAL_DB_BACKUP_DIR"],
        #         },
        #     },
        #     'default': {
        #         "BACKEND": "django.core.files.storage.FileSystemStorage",
        #     },
        #     'staticfiles': {
        #         "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        #     },
        # }

        # CRONTAB_COMMAND_SUFFIX = '2>&1'
        # CRONJOBS = [
        #     ('*/5 * * * *', 'cd ' + str(BASE_DIR) + ' && source virtual_env/bin/activate && python workload_management/manage.py dbbackup', '>> ' + os.path.join(BASE_DIR, 'backup/backup.log'))
        # ]
        ##############################


DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

#Key tenant settings
TENANT_MODEL = "landlord.School" # app.Model
TENANT_DOMAIN_MODEL = "landlord.Domain"  # app.Model

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Redirect to home URL after login (Default redirects to /accounts/profile/)
LOGIN_REDIRECT_URL = '/post_login_landing'
LOGOUT_REDIRECT_URL = '/accounts/login' 

#Tenant-aware media settings for user-uploaed media
STORAGES = {
    'default': {
        "BACKEND": "django_tenants.files.storage.TenantFileSystemStorage",
    },
    'staticfiles': {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}
MULTITENANT_RELATIVE_MEDIA_ROOT = "%s"  # (default: create sub-directory for each tenant)

MEDIA_ROOT = os.path.join(BASE_DIR,'media/')
MEDIA_URL = '/media/'
