# Generated by Django 4.1.2 on 2023-05-07 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eduload", "0063_programmeoffered_acad_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="programmeoffered",
            name="acad_year",
        ),
    ]
