# Generated by Django 3.2.12 on 2025-01-05 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eduload', '0097_survey_cohort_targeted'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlearningoutcome',
            name='cohort_valid_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cohort_valid_from', to='eduload.academicyear'),
        ),
        migrations.AddField(
            model_name='studentlearningoutcome',
            name='cohort_valid_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cohort_valid_to', to='eduload.academicyear'),
        ),
    ]
