# Generated by Django 5.0.1 on 2025-01-07 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eduload", "0099_auto_20250105_0409"),
    ]

    operations = [
        migrations.AddField(
            model_name="modulelearningoutcome",
            name="mlo_valid_from",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mlo_valid_from",
                to="eduload.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="modulelearningoutcome",
            name="mlo_valid_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mlo_valid_to",
                to="eduload.academicyear",
            ),
        ),
    ]
