# Generated by Django 6.0.5 on 2026-05-27 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eduload", "0136_alter_universitystaff_modules_in_menu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="universitystaff",
            name="homepage",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
    ]
