name: Django CI

on:
  push:
    branches: [ "devel" ]
  pull_request:
    branches: [ "devel" ]
env:
  DEVEL_DB_PASSWORD: "A*ino189"
  DJANGO_DEVEL_KEY: "cwrafo*vhbrweaoufvbsdvbnasdj-cnv"
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python workload_management/manage.py test workload_app.tests
